encoding: utf-8

markdown: kramdown
kramdown:
  input: GFM

highlighter: rouge
baseurl: /
paginate: 5

# excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
    - jekyll-paginate
    # - jekyll-sitemap
    # - jekyll-feed
    # - jemoji
#     - jekyll-mentions

# date_format: "%Y-%m-%d"  # e.g. 2014-07-03
# time_format: "%H:%M"     # 24 hour time

title: Zibiao-易仙居
description: To be a romantic coder . 
author: Zibiao Wu
email: zibiao-xd@outlook.com
